language: rust
os:
  - linux
  - osx
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - secure: L3jilKnridj1drhcGqH9g8mp3HwdK6iWGX7BSwxnrdEMJxuxAW2eK06cZw49MHwoDTqXBxfqROsA0GSMTNmuqxC58Zohlz7mCxfeH6ujPhhwW+TQl6E8hEuUKi0R07c9ofGXgEqF0ljFB0pRo88MDDhEsNotRy9VCo1gi82r744=
before_install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libsmpeg-dev libsqlite3-dev
before_script:
  - rustc -v
  - cargo -V
script:
  - make RUSTFLAGS= RUSTPKGFLAGS=
  - make doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
